apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  # revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
      # namespace: web-app
    spec:
      containers:
      - name: app1
        image: pujosn/web-app2:1.1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
        - containerPort: 9001
