apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"  # Pastikan ini sesuai dengan environment-mu
    networking.gke.io/managed-certificates: "app1-cert"
    kubernetes.io/ingress.global-static-ip-name: "web-app-ip-1" # Pastikan ini sudah dibuat di GCP
spec:
  rules:
    - host: takoples.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1-service
                port:
                  number: 9001
