apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-prod
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        namespace: production-ns
    spec:
      containers:
      - name: web-app
        image: pujosn/web-app2:1.1.0
        resources:
          limits:
            memory: "50"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/data"
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc-prod
        


---
apiVersion: v1
kind: Service
metadata:
  name: service-prod
  namespace: production-ns
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwo
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prod
  namespace: production-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  StorageClassName: standard-rwo

 
