apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-prod
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        namespace: production-ns
    spec:
      containers:
      - name: web-app
        image: pujosn/web-app2:1.1.0
        resources:
          limits:
            memory: "50"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pv-staging


---
apiVersion: v1
kind: Service
metadata:
  name: service-prod
  namespace: production-ns
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-staging
#   namespace: production-ns
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 15Gi
#   storageClassName: standard

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-staging
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
 
