apiVersion: v1
kind: Service
metadata:
  name: app1-service  
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  # loadBalancerIP: 34.101.37.31  # Ganti dengan IP static yang telah dicadangkan
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
