apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-jam-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-staging
  template:
    metadata:
      labels:
        app: web-staging
        namespace: staging-ns
    spec:
      containers:
      - name: web-staging
        image: pujosn/app-jam:1.2
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-volume
          mountPath: "/data"

      volumes: 
      - name: storage-volume
        persistentVolumeClaim:
          claimName: pvc-staging
       

---
apiVersion: v1
kind: Service
metadata:
  name: service-staging
  namespace: staging-ns
spec:
  type: ClusterIP
  selector:
    app: web-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80